name: CI
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
          BUILD_VERSION: 0.1.0.${{ github.run_number }}
        shell: pwsh
        run: |
          ./utilities/Deploy.ps1 -Clean -Test
          Write-Information -MessageData ([string]::Format("The output for build '{0}' was generated. Below is the content for the current deployment.", $env:BUILD_VERSION)) -InformationAction Continue
          Get-ChildItem -Path './deployment/marqueemodule' -Recurse
          Publish-Module -Path './deployment/marqueemodule' -NuGetApiKey $env:NUGET_KEY -Verbose
